services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
      - "8180:8180"
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
