FROM node:22-alpine3.20

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

COPY .env ./
COPY prisma ./prisma

EXPOSE 3000
EXPOSE 8180

RUN npx prisma generate

RUN npm run build

CMD ["npm", "start"]